package com.yl.greendaodemo.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yl.greendaodemo.db.Info;

import com.yl.greendaodemo.db.InfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig infoDaoConfig;

    private final InfoDao infoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        infoDaoConfig = daoConfigMap.get(InfoDao.class).clone();
        infoDaoConfig.initIdentityScope(type);

        infoDao = new InfoDao(infoDaoConfig, this);

        registerDao(Info.class, infoDao);
    }
    
    public void clear() {
        infoDaoConfig.getIdentityScope().clear();
    }

    public InfoDao getInfoDao() {
        return infoDao;
    }

}
